/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.io.File;
import javax.swing.JOptionPane;

/**
 * Descripcion: Interfaz para mostrar el contenido del grafo
 * @author mariv
 * @version 18/10/2023
 */
public class ModifyGraphs extends javax.swing.JFrame {
    ManejoTxt user = new ManejoTxt();
    private String [] filetxt;
    private File direcciontxt;
    
    public void setFiletxt(String[] filetxt) {
        this.filetxt = filetxt;
    }

    public void setDirecciontxt(File direcciontxt) {
        this.direcciontxt = direcciontxt;
    }
    

    /**
     * Creates new form ModifyGraphs
     */
    public ModifyGraphs() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarNombre = new javax.swing.JButton();
        TextNombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        AgregarNombre = new javax.swing.JButton();
        Box1 = new javax.swing.JComboBox<>();
        Box2 = new javax.swing.JComboBox<>();
        Relacionar = new javax.swing.JButton();
        Llenarbox = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boxUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        eliminarNombre.setForeground(new java.awt.Color(0, 0, 51));
        eliminarNombre.setText("Eliminar");
        eliminarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        TextNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TextNombre.setForeground(new java.awt.Color(102, 102, 102));
        TextNombre.setText("Agrege el nombre de usuario (@ejemplo)");
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("<--");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        AgregarNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        AgregarNombre.setForeground(new java.awt.Color(0, 0, 51));
        AgregarNombre.setText("Agregar");
        AgregarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        Box1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Box1.setForeground(new java.awt.Color(0, 0, 51));
        Box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box1ActionPerformed(evt);
            }
        });
        getContentPane().add(Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        Box2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Box2.setForeground(new java.awt.Color(0, 0, 51));
        Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2ActionPerformed(evt);
            }
        });
        getContentPane().add(Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        Relacionar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Relacionar.setForeground(new java.awt.Color(0, 0, 51));
        Relacionar.setText("Relacionar");
        Relacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelacionarActionPerformed(evt);
            }
        });
        getContentPane().add(Relacionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        Llenarbox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Llenarbox.setForeground(new java.awt.Color(0, 0, 51));
        Llenarbox.setText("Ver Usuarios");
        Llenarbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlenarboxActionPerformed(evt);
            }
        });
        getContentPane().add(Llenarbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        boxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(boxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/imagenmodi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    public void setDato(ManejoTxt user){
        this.user = user;
    }
    
    
    /**
     * Descripcion: Regresa a la interfaz principal
     * @autor: Maria Martinez
     * @version: 29/09/23
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /**
         * Descripcion: El main de la interfaz principal
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setDato(user);
                main.setFiletxt(filetxt);
                main.setDirecciontxt(direcciontxt);
                main.setVisible(true);
            }
        });
        
        // Ocultar esta interfaz
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed
 /**
     * Descripcion: elimina un usuario en el txt utilizado y genera el grafo
     * @autor: Andrea Reyes
     * @version: 20/10/23
     * @param evt
     */
   
    private void eliminarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarNombreActionPerformed
     
        if (boxUsuarios.getSelectedItem()!=  null){
        Grafo grafito = new Grafo(filetxt.length-1);
        String usuario= boxUsuarios.getSelectedItem().toString().replaceAll("\\p{C}", "");
        setFiletxt(grafito.eliminarUsuario(usuario, filetxt));
        user.Save(filetxt);
        LlenarboxActionPerformed(evt);
        
      }else{
          JOptionPane.showMessageDialog(null, "Error! \n Cargue los usuarios");
      
      
      }
    }//GEN-LAST:event_eliminarNombreActionPerformed

    /**
     * Descripcion: Agrega un usuario al txt utilizado para generar el grafo
     * @autor: Mauricio Mendez
     * @version: 18/10/23
     * @param evt
     */
    
    private void AgregarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNombreActionPerformed
        Grafo nuevografo = new Grafo(filetxt.length+1);
        String nombre = TextNombre.getText();
        TextNombre.setText("Agrege el nombre de usuario (@ejemplo)");
        setFiletxt(nuevografo.AñadirUsuario(nombre, filetxt));
        user.Save(filetxt);
        LlenarboxActionPerformed(evt);

    }//GEN-LAST:event_AgregarNombreActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    
    /**
     * Descripcion: Llena los combobox con la informacion del grafo
     * @autor: Mauricio Mendez y Andrea Reyes
     * @version: 18/10/23
     * @param evt
     */
    private void LlenarboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlenarboxActionPerformed
       
        boxUsuarios.removeAllItems();
        Box1.removeAllItems();
        Box2.removeAllItems();
        
            for (int i = 1; !filetxt[i].replaceAll("\\p{C}", "").equals("relaciones"); i++) {
                Box1.addItem(filetxt[i].replaceAll("\\p{C}", ""));
                Box2.addItem(filetxt[i].replaceAll("\\p{C}", ""));
                boxUsuarios.addItem(filetxt[i].replaceAll("\\p{C}", "")); 
            }
    }//GEN-LAST:event_LlenarboxActionPerformed

    
    /**
     * Descripcion: Agrega una coneccion entre usuarios al txt utilizado para generar el grafo
     * @autor: Mauricio Mendez
     * @version: 18/10/23
     * @param evt
     */
    private void RelacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelacionarActionPerformed
        if (Box1.getSelectedItem() != null){
            Grafo nuevografo = new Grafo(filetxt.length+1);
            if(Box1.getSelectedItem().toString().equals(Box2.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "Error! \n Se deben relacionar ususarios diferentes.");
            }else{
                String relacion = Box1.getSelectedItem().toString()+", "+Box2.getSelectedItem();
                setFiletxt(nuevografo.RelacionarUsuario(relacion, filetxt));
                user.Save(filetxt);
            }
        } else{
            JOptionPane.showMessageDialog(null, "Error! \n Cargue los usuarios");
        }
        

    }//GEN-LAST:event_RelacionarActionPerformed

    
    private void boxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxUsuariosActionPerformed

    private void Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box2ActionPerformed

    private void Box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyGraphs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyGraphs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyGraphs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyGraphs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyGraphs().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNombre;
    private javax.swing.JComboBox<String> Box1;
    private javax.swing.JComboBox<String> Box2;
    private javax.swing.JButton Llenarbox;
    private javax.swing.JButton Relacionar;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JComboBox<String> boxUsuarios;
    private javax.swing.JButton eliminarNombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
